CREATE TABLE "user" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "external_user_id" BIGINT,
  "username" VARCHAR(100),
  "first_name" VARCHAR(100),
  "last_name" VARCHAR(100),
  "created_at" TIMESTAMP DEFAULT 'now()'
);

CREATE TABLE "organization" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255)
);

CREATE TABLE "chat" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "external_chat_id" BIGINT,
  "organization_id" BIGINT NOT NULL,
  "type" VARCHAR(50),
  "title" VARCHAR(255),
  "chat_username" VARCHAR(100),
  "created_at" TIMESTAMP DEFAULT 'now()'
);

CREATE TABLE "user_organization_links" (
  "user_id" BIGINT,
  "organization_id" BIGINT,
  "role_id" BIGINT,
  "joined_at" TIMESTAMP DEFAULT 'now()',
  PRIMARY KEY ("user_id", "organization_id", "role_id")
);

CREATE TABLE "data_table" (
  "id" BIGSERIAL PRIMARY KEY,
  "organization_id" BIGINT NOT NULL,
  "table_name" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMP DEFAULT 'now()'
);

CREATE TABLE "table_column" (
  "id" BIGSERIAL PRIMARY KEY,
  "table_id" BIGINT NOT NULL,
  "column_name" VARCHAR(255) NOT NULL,
  "column_type" VARCHAR(50) NOT NULL
);

CREATE TABLE "table_data_metadata" (
  "id" BIGSERIAL PRIMARY KEY,
  "table_id" BIGINT NOT NULL,
  "mongo_document_id" UUID UNIQUE NOT NULL,
  "user_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP DEFAULT 'now()',
  "action" VARCHAR(50)
);

CREATE TABLE "audit_logs" (
  "id" BIGSERIAL PRIMARY KEY,
  "user_id" BIGINT,
  "table_id" BIGINT,
  "action" VARCHAR(50),
  "timestamp" TIMESTAMP DEFAULT 'now()'
);

CREATE TABLE "role" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" BIGINT NOT NULL,
  "role_name" VARCHAR(50) NOT NULL
);

CREATE TABLE "role_organization_permission" (
  "role_id" BIGINT NOT NULL,
  "organization_id" BIGINT NOT NULL,
  "permission" VARCHAR(100) NOT NULL
);

CREATE TABLE "role_table_permission" (
  "role_id" BIGINT NOT NULL,
  "table_id" BIGINT NOT NULL,
  "permission" VARCHAR(100) NOT NULL
);

CREATE UNIQUE INDEX ON "chat" ("organization_id", "title");

CREATE UNIQUE INDEX ON "data_table" ("organization_id", "table_name");

CREATE UNIQUE INDEX ON "table_column" ("table_id", "column_name");

CREATE INDEX ON "table_data_metadata" ("user_id");

CREATE INDEX ON "table_data_metadata" ("created_at");

CREATE INDEX ON "audit_logs" ("timestamp");

CREATE UNIQUE INDEX ON "role" ("organization_id", "role_name");

CREATE UNIQUE INDEX ON "role_organization_permission" ("role_id", "organization_id", "permission");

CREATE UNIQUE INDEX ON "role_table_permission" ("role_id", "table_id", "permission");

ALTER TABLE "chat" ADD FOREIGN KEY ("organization_id") REFERENCES "organization" ("id");

ALTER TABLE "user_organization_links" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "user_organization_links" ADD FOREIGN KEY ("organization_id") REFERENCES "organization" ("id");

ALTER TABLE "user_organization_links" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "table_column" ADD FOREIGN KEY ("table_id") REFERENCES "data_table" ("id");

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("table_id") REFERENCES "data_table" ("id");

ALTER TABLE "table_data_metadata" ADD FOREIGN KEY ("table_id") REFERENCES "data_table" ("id");

ALTER TABLE "table_data_metadata" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "role_organization_permission" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "role_table_permission" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "role_table_permission" ADD FOREIGN KEY ("table_id") REFERENCES "data_table" ("id");

ALTER TABLE "role_organization_permission" ADD FOREIGN KEY ("organization_id") REFERENCES "organization" ("id");

ALTER TABLE "data_table" ADD FOREIGN KEY ("organization_id") REFERENCES "organization" ("id");

ALTER TABLE "role" ADD FOREIGN KEY ("organization_id") REFERENCES "organization" ("id");
