services:
  # PostgreSQ
  postgres_app:
    container_name: postgres_container
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_app:/data/postgres
    networks:
     - logistic_network
    ports:
     - "5432:5432"
    restart: unless-stopped

  # MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    env_file: .env
    networks:
      - logistic_network
    volumes:
      - mongo_data:/data/db

  # Redis
  redis:
    container_name: redis_container
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"
    env_file: .env
    networks:
      - logistic_network
    command: [ "redis-server", "--save", "" ]

  app:
    build:
      context: ./
    image: kotlin-spring-app
    container_name: LogiBot
    ports:
      - "8080:8080"
    networks:
      - dev-net
      - logistic_network
    env_file: .env
    restart: "no"

networks:
  logistic_network:
    driver: bridge
  dev-net:
    driver: bridge

volumes:
  postgres_app:
  mongo_data: