spring:

  liquibase:
    enabled: true # Включение Liquibase для управления миграциями базы данных

  transaction:
    default-timeout: 30 # Таймаут транзакций в секундах
    isolation-level: DEFAULT # Уровень изоляции транзакций, например, REPEATABLE_READ/READ_COMMITTED/SERIALIZABLE

#  security:
#    user:
#      name: admin # Имя пользователя для базовой авторизации в dev-среде
#      password: secret # Пароль для базовой авторизации в dev-среде
#    oauth2:
#      resource server:
#        jwt:
#          issuer-uri: https://auth.example.com # URL авторизационного сервера для проверки JWT-токенов

  datasource:
    driver-class-name: org.postgresql.Driver # Драйвер для подключения к PostgreSQL
    url: ${DB_URL:jdbc:postgresql://localhost:5432/logistic} # URL подключения к базе данных
    username: ${DB_USERNAME:logistic} # Имя пользователя базы данных
    password: ${DB_PASSWORD:logistic} # Пароль пользователя базы данных
    hikari:
      minimum-idle: 5 # Минимальное количество соединений в пуле
      maximum-pool-size: 20 # Максимальное количество соединений в пуле
      idle-timeout: 30000 # Время простоя соединения перед его закрытием (в миллисекундах)
      max-lifetime: 1800000 # Максимальное время жизни соединения в пуле (в миллисекундах)
      connection-timeout: 20000 # Максимальное время ожидания соединения из пула (в миллисекундах)
      pool-name: HikariPool-Logistic # Название пула соединений

  jpa:
    open-in-view: false # Отключение Open Session in View, чтобы избежать ленивых загрузок после закрытия транзакции
    show-sql: false # Отключение отображения SQL-запросов в логах
    properties:
      hibernate:
        format_sql: false # Отключение форматирования SQL-запросов
        generate_statistics: false # Отключение сбора статистики Hibernate для повышения производительности
        default_schema: public # Схема базы данных по умолчанию
    hibernate:
      ddl-auto: none # Отключение автоматического управления схемой базы данных (создание/обновление таблиц)
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis # Тип используемого кэша, например, caffeine, redis, ehcache
  data:
    redis:
      host: ${REDIS_HOST:localhost} # Хост Redis
      port: ${REDIS_PORT:6379} # Порт Redis
      password: ${CACHE_PASSWORD:} # Пароль Redis
      timeout: 100 # Таймаут подключения к Redis (в миллисекундах)
      database: 0

    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:tables}
      username: ${MONGO_USERNAME:logistic}
      password: ${MONGO_PASSWORD:logistic}
      authentication-database: ${MONGO_AUTH:admin}

webServer:
  domainName: ${WEB_DOMAIN_NAME}

telegrambots:
  enabled: true # Включение TelegramBots
  bots:
    - username: ${TELEGRAM_BOT_USERNAME} # Имя пользователя бота
      token: ${TELEGRAM_BOT_TOKEN} # Токен доступа бота
#      path: ${TELEGRAM_WEBHOOK_PATH} # URL для вебхука (если используется)

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans # Перечень доступных веб-эндпоинтов для мониторинга
  health:
    db:
      enabled: true # Включение проверки состояния базы данных
    redis:
      enabled: true # Включение проверки состояния Redis
  info:
    app:
      name: LogisticBot # Название приложения для эндпоинта /actuator/info
      description: API для логистической компании # Описание приложения для эндпоинта /actuator/info

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg%n"
  level:
    ru.tutko.micro.logibot.telegram.dispatcher.UpdateDispatcher: INFO
    root: INFO  # Уровень логирования по умолчанию
    ru.tutko.micro.logibot: DEBUG  # Детальное логирование для проекта
    com.zaxxer.hikari: WARN  # Логирование HikariCP на уровне WARN
    org.telegram: INFO  # Telegram API
    org.hibernate: WARN  # Hibernate
    org.springframework.security: WARN  # Spring Security
  file:
    name: /var/log/logistic-bot.log  # Полный путь к файлу логов

springdoc:
  api-docs:
    enabled: true # Включение генерации документации OpenAPI
  swagger-ui:
    enabled: true # Включение Swagger UI для визуализации документации
