driver=org.postgresql.Driver
url=jdbc:postgresql://localhost:5432/logistic
username=logistic
password=logistic
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
outputChangeLogFile=src/main/resources/db/changelog/db.changelog-generated.yaml
verbose=true
enabled=true
default-schema=public